"use client";

/**
 * Career Path — the reward at the end of a domain's roadmap. Unlocked only
 * once every topic is completed (same gate as interview prep; admins can
 * preview). Generated by the LLM from the learner's onboarding persona
 * (experience x goal x pace): career stages with pace-adjusted timeframes,
 * a real certification ladder, role/salary progression for the Indian
 * market, portfolio projects and three do-this-week first steps.
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { isAxiosError } from "axios";
import {
  ArrowLeft,
  Award,
  Briefcase,
  CheckCircle2,
  Compass,
  Flag,
  FolderGit2,
  Lock,
  RefreshCcw,
  Rocket,
  Star,
} from "lucide-react";
import { motion, useReducedMotion } from "framer-motion";

import { Button } from "@/components/ui/button";
import {
  apiErrorMessage,
  fetchCareerPath,
  type CareerPath,
} from "@/lib/api";
import { cn } from "@/lib/utils";

const EASE = [0.22, 1, 0.36, 1] as const;

const CERT_LEVEL_STYLES: Record<string, { badge: string; label: string }> = {
  foundation: { badge: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30", label: "Foundation" },
  intermediate: { badge: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30", label: "Intermediate" },
  advanced: { badge: "bg-violet-500/15 text-violet-300 border-violet-500/30", label: "Advanced" },
  expert: { badge: "bg-amber-500/15 text-amber-300 border-amber-500/30", label: "Expert" },
};

const SENIORITY_STYLES: Record<string, string> = {
  entry: "text-emerald-300",
  mid: "text-cyan-300",
  senior: "text-violet-300",
  lead: "text-amber-300",
};

// Rotating status lines for the (potentially 20-40s) cold generation.
const LOADING_LINES = [
  "Reading your profile…",
  "Charting career stages for your pace…",
  "Picking certifications that actually matter…",
  "Mapping roles and salary bands…",
  "Choosing portfolio projects…",
  "Almost there — polishing your roadmap…",
];

const PERSONA_LABELS: Record<string, string> = {
  none: "Starting fresh",
  some: "Some experience",
  experienced: "Experienced",
  interview: "Interview-focused",
  awareness: "Building awareness",
  curiosity: "Curiosity-driven",
  relaxed: "Relaxed pace",
  standard: "Standard pace",
  intense: "Intense pace",
};

export default function CareerPathPage() {
  const params = useParams<{ slug: string }>();
  const slug = params?.slug;

  const [career, setCareer] = useState<CareerPath | null>(null);
  const [adminOverride, setAdminOverride] = useState(false);
  const [loading, setLoading] = useState(true);
  const [locked, setLocked] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback((s: string) => {
    setLoading(true);
    setError(null);
    setLocked(false);
    fetchCareerPath(s)
      .then(({ career, gate }) => {
        setCareer(career);
        setAdminOverride(!!gate.adminOverride);
      })
      .catch((err) => {
        // 403 = roadmap not fully completed — the honest "locked" state
        // (deep-linked here without earning it).
        if (isAxiosError(err) && err.response?.status === 403) {
          setLocked(true);
        } else {
          setError(apiErrorMessage(err, "Could not chart your career path"));
        }
      })
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (slug) load(slug);
  }, [slug, load]);

  return (
    <main className="mx-auto max-w-5xl px-4 pb-24 pt-10 lg:px-8">
      <Link
        href={slug ? `/domains/${slug}` : "/domains"}
        className="inline-flex items-center gap-1.5 text-sm text-muted-foreground transition hover:text-foreground"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to roadmap
      </Link>

      <div className="mt-6 flex items-center gap-2 text-xs uppercase tracking-[0.25em] text-primary">
        <Compass className="h-4 w-4" />
        Career path
      </div>

      {loading ? (
        <LoadingState />
      ) : locked ? (
        <LockedState slug={slug} />
      ) : error ? (
        <div className="mt-16 flex flex-col items-center text-center">
          <p className="text-sm text-destructive">{error}</p>
          <Button variant="outline" className="mt-4" onClick={() => slug && load(slug)}>
            <RefreshCcw className="h-4 w-4" /> Try again
          </Button>
        </div>
      ) : career ? (
        <CareerView career={career} adminOverride={adminOverride} />
      ) : null}
    </main>
  );
}

function LockedState({ slug }: { slug?: string }) {
  return (
    <div className="mt-16 flex flex-col items-center text-center">
      <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-muted/40">
        <Lock className="h-6 w-6 text-muted-foreground" />
      </span>
      <p className="mt-4 text-sm font-medium text-foreground">
        Your career path is waiting at the end of the roadmap.
      </p>
      <p className="mt-1.5 max-w-sm text-xs text-muted-foreground">
        Complete every topic in this domain to unlock your personalized career
        map — stages, certifications, roles and salaries.
      </p>
      <Button asChild variant="outline" className="mt-5">
        <Link href={slug ? `/domains/${slug}` : "/domains"}>
          <ArrowLeft className="h-4 w-4" /> Back to the roadmap
        </Link>
      </Button>
    </div>
  );
}

function LoadingState() {
  const [i, setI] = useState(0);
  useEffect(() => {
    const t = setInterval(() => setI((v) => (v + 1) % LOADING_LINES.length), 3200);
    return () => clearInterval(t);
  }, []);
  return (
    <div className="mt-20 flex flex-col items-center text-center">
      <Compass className="h-10 w-10 animate-[spin_5s_linear_infinite] text-primary/70" />
      <p className="mt-5 text-sm font-medium text-foreground">
        Charting your career roadmap
      </p>
      <p className="mt-1.5 min-h-5 text-xs text-muted-foreground" aria-live="polite">
        {LOADING_LINES[i]}
      </p>
      <p className="mt-6 max-w-sm text-xs text-muted-foreground/60">
        First generation for a persona takes up to ~30 seconds. After that it
        loads instantly.
      </p>
    </div>
  );
}

function Section({
  icon,
  title,
  sub,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  sub?: string;
  children: React.ReactNode;
}) {
  const reduce = useReducedMotion();
  return (
    <motion.section
      initial={reduce ? { opacity: 1 } : { opacity: 0, y: 18 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.15 }}
      transition={{ duration: 0.5, ease: EASE }}
      className="mt-16"
    >
      <div className="flex items-center gap-2.5">
        <span className="inline-flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
          {icon}
        </span>
        <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
      </div>
      {sub && <p className="mt-1.5 text-sm text-muted-foreground">{sub}</p>}
      <div className="mt-6">{children}</div>
    </motion.section>
  );
}

function CareerView({
  career,
  adminOverride,
}: {
  career: CareerPath;
  adminOverride: boolean;
}) {
  const personaChips = useMemo(
    () =>
      [career.persona.level, career.persona.goal, career.persona.pace].map(
        (p) => PERSONA_LABELS[p] ?? p
      ),
    [career.persona]
  );

  return (
    <div>
      {/* ── Headline ── */}
      <div className="mt-8">
        <p className="inline-flex items-center gap-1.5 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
          <Star className="h-3 w-3 fill-current" />
          {adminOverride
            ? "Admin preview"
            : `Roadmap completed — your ${career.domainName} career map`}
        </p>
        <h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
          {career.headline}
        </h1>
        <p className="mt-3 max-w-2xl text-sm leading-relaxed text-muted-foreground sm:text-base">
          {career.summary}
        </p>
        <div className="mt-4 flex flex-wrap gap-2">
          {personaChips.map((c) => (
            <span
              key={c}
              className="rounded-full border border-border bg-card/50 px-2.5 py-1 text-[11px] text-muted-foreground"
            >
              {c}
            </span>
          ))}
          <span className="rounded-full border border-border bg-card/50 px-2.5 py-1 text-[11px] text-muted-foreground">
            Tailored to {career.domainName}
          </span>
        </div>
      </div>

      {/* ── This week ── */}
      <Section
        icon={<Rocket className="h-4 w-4" />}
        title="Start this week"
        sub="Three small moves to put you on the road today."
      >
        <ol className="grid gap-3 sm:grid-cols-3">
          {career.firstSteps.map((s, i) => (
            <li
              key={i}
              className="rounded-xl border border-border bg-card/50 p-4 text-sm leading-relaxed"
            >
              <span className="font-mono text-xs text-primary">0{i + 1}</span>
              <p className="mt-1.5 text-foreground/90">{s}</p>
            </li>
          ))}
        </ol>
      </Section>

      {/* ── The road (stages timeline) ── */}
      <Section
        icon={<Flag className="h-4 w-4" />}
        title="The road"
        sub="Your stages, in order — timeframes already adjusted to your pace."
      >
        <ol className="relative space-y-8 border-l border-border/60 pl-8">
          {career.stages.map((st) => (
            <li key={st.phase} className="relative">
              {/* node */}
              <span className="absolute -left-[41px] flex h-6 w-6 items-center justify-center rounded-full border border-primary/40 bg-background font-mono text-[11px] text-primary">
                {st.phase}
              </span>
              <div className="rounded-2xl border border-border bg-card/50 p-5">
                <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
                  <h3 className="text-base font-semibold text-foreground">
                    {st.title}
                  </h3>
                  <span className="rounded-full bg-primary/10 px-2 py-0.5 font-mono text-[11px] text-primary">
                    {st.timeframe}
                  </span>
                </div>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  {st.focus}
                </p>
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {st.skills.map((sk) => (
                    <span
                      key={sk}
                      className="rounded-md border border-border/70 bg-background/60 px-2 py-0.5 text-[11px] text-foreground/80"
                    >
                      {sk}
                    </span>
                  ))}
                </div>
                <p className="mt-3 flex items-start gap-1.5 text-xs text-emerald-300/90">
                  <CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                  <span>
                    <span className="font-medium">Done when:</span> {st.milestone}
                  </span>
                </p>
              </div>
            </li>
          ))}
        </ol>
      </Section>

      {/* ── Certification ladder ── */}
      <Section
        icon={<Award className="h-4 w-4" />}
        title="Certification ladder"
        sub="Real, hiring-relevant certifications — cheapest and easiest first."
      >
        <div className="grid gap-3 sm:grid-cols-2">
          {career.certifications.map((c) => {
            const style = CERT_LEVEL_STYLES[c.level] ?? CERT_LEVEL_STYLES.foundation;
            return (
              <div
                key={c.name}
                className="rounded-2xl border border-border bg-card/50 p-5"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h3 className="text-sm font-semibold text-foreground">{c.name}</h3>
                    <p className="mt-0.5 text-xs text-muted-foreground">{c.org}</p>
                  </div>
                  <span
                    className={cn(
                      "shrink-0 rounded-full border px-2 py-0.5 text-[10px] font-medium uppercase tracking-wide",
                      style.badge
                    )}
                  >
                    {style.label}
                  </span>
                </div>
                <p className="mt-3 text-xs leading-relaxed text-muted-foreground">
                  {c.whyItMatters}
                </p>
                <div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-foreground/70">
                  <span>
                    <span className="text-muted-foreground">When:</span> {c.whenToTake}
                  </span>
                  <span>
                    <span className="text-muted-foreground">Cost:</span> {c.cost}
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </Section>

      {/* ── Role progression ── */}
      <Section
        icon={<Briefcase className="h-4 w-4" />}
        title="Where it takes you"
        sub="Role progression with realistic Indian-market salary bands."
      >
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {career.roles.map((r, i) => (
            <div
              key={r.title}
              className="relative rounded-2xl border border-border bg-card/50 p-5"
            >
              <p className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                Step {i + 1}
              </p>
              <h3 className={cn("mt-1 text-sm font-semibold", SENIORITY_STYLES[r.seniority])}>
                {r.title}
              </h3>
              <p className="mt-2 text-lg font-bold tabular-nums text-foreground">
                {r.salaryRange}
              </p>
              <p className="mt-1.5 text-[11px] leading-relaxed text-muted-foreground">
                {r.whenReady}
              </p>
            </div>
          ))}
        </div>
      </Section>

      {/* ── Portfolio projects ── */}
      <Section
        icon={<FolderGit2 className="h-4 w-4" />}
        title="Prove it with projects"
        sub="Portfolio pieces that make recruiters stop scrolling — easiest first."
      >
        <div className="grid gap-3 lg:grid-cols-3">
          {career.projects.map((p) => (
            <div key={p.title} className="rounded-2xl border border-border bg-card/50 p-5">
              <h3 className="text-sm font-semibold text-foreground">{p.title}</h3>
              <p className="mt-2 text-xs leading-relaxed text-muted-foreground">
                {p.description}
              </p>
              <div className="mt-3 flex flex-wrap gap-1.5">
                {p.skills.map((sk) => (
                  <span
                    key={sk}
                    className="rounded-md border border-border/70 bg-background/60 px-2 py-0.5 text-[11px] text-foreground/80"
                  >
                    {sk}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </Section>

      <p className="mt-16 text-center text-xs text-muted-foreground/60">
        Generated from your onboarding answers — experience, goal and pace.
        Salary bands are indicative, not guarantees.
      </p>
    </div>
  );
}
